#!/usr/bin/env python3
"""
telemetry-rollup.py

Reads .orchestrator/docs/ops/agent-telemetry.jsonl and writes a per-stage/per-agent markdown summary to
.orchestrator/docs/ops/telemetry-rollup.md: run counts, success rate, retry rate, average duration for
successful runs, and infra-error visibility. This is what makes "is the chain healthy" answerable
at a glance instead of grepping the raw JSONL log.

Usage:
    python3 .orchestrator/scripts/telemetry-rollup.py --input .orchestrator/docs/ops/agent-telemetry.jsonl \
        --output .orchestrator/docs/ops/telemetry-rollup.md
"""

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone


def load_entries(path):
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path, "r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(
                    f"WARNING: skipping malformed line {line_number} in {path}: {e}",
                    file=sys.stderr,
                )
    return entries


def build_rollup(entries):
    # Keyed by (stage, agent) - a stage can in principle be handled by more than one agent
    # (e.g. Implementation: backend-builder / frontend-builder), so don't collapse across agents.
    buckets = defaultdict(lambda: {
        "success": 0, "fail": 0, "timeout": 0, "infra_error": 0,
        "success_duration_total": 0, "success_duration_count": 0,
        "tokens_input_total": 0, "tokens_output_total": 0, "tokens_reported_count": 0,
    })
    feature_slugs = set()
    features_released = set()

    for e in entries:
        stage = e.get("stage", "unknown")
        agent = e.get("agent", "unknown")
        outcome = e.get("outcome", "unknown")
        slug = e.get("feature_slug")
        if slug:
            feature_slugs.add(slug)
            if agent == "release-engineer" and outcome == "success":
                features_released.add(slug)

        bucket = buckets[(stage, agent)]
        if outcome in bucket:
            bucket[outcome] += 1
        if outcome == "success":
            duration = e.get("duration_seconds")
            if isinstance(duration, (int, float)):
                bucket["success_duration_total"] += duration
                bucket["success_duration_count"] += 1

        # Best-effort and optional (see log-agent-run.sh) - only present when an agent's runtime
        # actually reported it. Absent on most entries; that's expected, not a data-quality bug.
        tokens_input = e.get("tokens_input")
        tokens_output = e.get("tokens_output")
        if isinstance(tokens_input, (int, float)) or isinstance(tokens_output, (int, float)):
            bucket["tokens_input_total"] += tokens_input if isinstance(tokens_input, (int, float)) else 0
            bucket["tokens_output_total"] += tokens_output if isinstance(tokens_output, (int, float)) else 0
            bucket["tokens_reported_count"] += 1

    return buckets, feature_slugs, features_released


def format_rollup(buckets, feature_slugs, features_released):
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = []
    lines.append("# Telemetry rollup")
    lines.append("")
    lines.append(
        "Auto-generated by `.github/workflows/telemetry-rollup.yml` from "
        "`.orchestrator/docs/ops/agent-telemetry.jsonl` — do not hand-edit, it will be overwritten on the next "
        "scheduled run."
    )
    lines.append("")
    lines.append(f"**Last generated:** {generated_at}")
    lines.append("")

    if not buckets:
        lines.append(
            "No telemetry recorded yet — nothing has logged a terminal outcome via "
            "`.orchestrator/scripts/log-agent-run.sh` so far."
        )
        lines.append("")
        return "\n".join(lines)

    lines.append(
        f"**Features tracked:** {len(feature_slugs)} · **Reached Release Engineer success:** "
        f"{len(features_released)}"
    )
    lines.append("")
    lines.append(
        "`infra_error` is shown for visibility only — it never counts toward `retry_rate` or "
        "`success_rate`, since it isn't a quality signal (see `commit-and-handoff.skill.md`)."
    )
    lines.append("")
    lines.append(
        "Token columns are best-effort: many entries won't have them at all, since not every "
        "agent runtime can report its own usage (see `log-agent-run.sh`). `n/a` means "
        "\"not reported,\" not \"zero.\""
    )
    lines.append("")
    lines.append(
        "| Stage | Agent | Runs | Success | Fail | Timeout | Infra errors | Success rate | "
        "Retry rate | Avg duration (success) | Avg tokens in/out (reported runs) |"
    )
    lines.append(
        "|---|---|---|---|---|---|---|---|---|---|---|"
    )

    for (stage, agent), b in sorted(buckets.items()):
        quality_total = b["success"] + b["fail"] + b["timeout"]
        total_runs = quality_total + b["infra_error"]
        success_rate = f"{(b['success'] / quality_total * 100):.0f}%" if quality_total else "n/a"
        retry_rate = (
            f"{((b['fail'] + b['timeout']) / quality_total * 100):.0f}%" if quality_total else "n/a"
        )
        avg_duration = (
            f"{(b['success_duration_total'] / b['success_duration_count']):.0f}s"
            if b["success_duration_count"] else "n/a"
        )
        if b["tokens_reported_count"]:
            avg_tokens_in = round(b["tokens_input_total"] / b["tokens_reported_count"])
            avg_tokens_out = round(b["tokens_output_total"] / b["tokens_reported_count"])
            avg_tokens = f"{avg_tokens_in:,} / {avg_tokens_out:,} (n={b['tokens_reported_count']})"
        else:
            avg_tokens = "n/a"
        lines.append(
            f"| {stage} | {agent} | {total_runs} | {b['success']} | {b['fail']} | "
            f"{b['timeout']} | {b['infra_error']} | {success_rate} | {retry_rate} | "
            f"{avg_duration} | {avg_tokens} |"
        )

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    entries = load_entries(args.input)
    buckets, feature_slugs, features_released = build_rollup(entries)
    output = format_rollup(buckets, feature_slugs, features_released)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Wrote rollup for {len(entries)} entries to {args.output}")


if __name__ == "__main__":
    main()
